# lexer_runner.py - DFA-based lexer execution and standalone lexer generation


def run_lexer(dfa_start, text, skip_actions=None):
    """
    Run DFA lexer on text using longest-match.
    skip_actions: set of token names whose tokens should be skipped (e.g., whitespace).
    Returns (tokens, errors).
      tokens: list of (token_name, lexeme, line, col)
      errors: list of (line, col, char)
    """
    if skip_actions is None:
        skip_actions = set()

    tokens = []
    errors = []
    pos = 0
    line = 1
    col = 1

    def pos_to_lc(p):
        ln, cl = 1, 1
        for ch in text[:p]:
            if ch == '\n':
                ln += 1
                cl = 1
            else:
                cl += 1
        return ln, cl

    while pos < len(text):
        state = dfa_start
        last_accept = None
        last_accept_pos = pos
        i = pos

        while i < len(text):
            c = text[i]
            if c in state.transitions:
                state = state.transitions[c]
                if state.accept is not None:
                    last_accept = state.accept
                    last_accept_pos = i + 1
                i += 1
            else:
                break

        if last_accept is not None:
            lexeme = text[pos:last_accept_pos]
            if last_accept not in skip_actions:
                ln, cl = pos_to_lc(pos)
                tokens.append((last_accept, lexeme, ln, cl))
            pos = last_accept_pos
        else:
            ln, cl = pos_to_lc(pos)
            errors.append((ln, cl, text[pos]))
            pos += 1

    return tokens, errors


def generate_standalone_lexer(dfa_start, all_states, skip_token_names, output_path):
    """Generate a standalone Python lexer file from the DFA."""
    transitions = {}
    accept_states = {}
    for s in all_states:
        if s.transitions:
            transitions[s.id] = {sym: t.id for sym, t in s.transitions.items()}
        if s.accept:
            accept_states[s.id] = s.accept

    skip_repr = repr(set(skip_token_names))

    code = f'''# Auto-generated lexer — standalone, no dependency on the generator.
# Generated by YALex Generator.

START_STATE = {dfa_start.id}

TRANSITIONS = {repr(transitions)}

ACCEPT_STATES = {repr(accept_states)}

SKIP_TOKENS = {skip_repr}


def tokenize(text, skip_tokens=SKIP_TOKENS):
    """Tokenize input text using the DFA. Returns (tokens, errors)."""
    tokens = []
    errors = []
    pos = 0

    def get_lc(p):
        ln, cl = 1, 1
        for ch in text[:p]:
            if ch == '\\n':
                ln += 1
                cl = 1
            else:
                cl += 1
        return ln, cl

    while pos < len(text):
        state = START_STATE
        last_accept = None
        last_accept_pos = pos
        i = pos

        while i < len(text):
            c = text[i]
            if state in TRANSITIONS and c in TRANSITIONS[state]:
                state = TRANSITIONS[state][c]
                if state in ACCEPT_STATES:
                    last_accept = ACCEPT_STATES[state]
                    last_accept_pos = i + 1
                i += 1
            else:
                break

        if last_accept is not None:
            lexeme = text[pos:last_accept_pos]
            if last_accept not in skip_tokens:
                ln, cl = get_lc(pos)
                tokens.append((last_accept, lexeme, ln, cl))
            pos = last_accept_pos
        else:
            ln, cl = get_lc(pos)
            errors.append((ln, cl, text[pos]))
            pos += 1

    return tokens, errors


if __name__ == "__main__":
    import sys
    if len(sys.argv) < 2:
        print("Usage: python generated_lexer.py <input_file>")
        sys.exit(1)
    with open(sys.argv[1], "r", encoding="utf-8") as f:
        text = f.read()
    toks, errs = tokenize(text)
    print("=== TOKENS ===")
    for name, lexeme, ln, cl in toks:
        print(f"  {{name:<15}} {{repr(lexeme):<25}} line {{ln}}, col {{cl}}")
    if errs:
        print("\\n=== ERRORS ===")
        for ln, cl, ch in errs:
            print(f"  Unexpected {{repr(ch)}} at line {{ln}}, col {{cl}}")
    else:
        print("\\nNo errors found.")
'''
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(code)
